apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/rvennam/mynodehttp:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/rvennam/mynodehttp:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: mynodehttp
        chartPath: charts/mynodehttp
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/rvennam/mynodehttp"
          image.tag: "{{.TAG}}"
